remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: my development website
description: just a development website for me to play with
email: test@bruett.com
twitter_username: johnbruett
github_username: jbruett