title: my development website
description: just a development website for me to play with
email: test@bruett.com
twitter_username: johnbruett

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

exclude: ["README.md", "**/README.md"]

timezone: America/New_York

show_drafts: FALSE