remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: my development website
description: just a development website for me to play with
email: test@bruett.com
twitter_username: johnbruett
domain: dev.bruett.com
url: https://dev.bruett.com
permalink: "/:title"

author:
  name: John Bruett
